#pragma once

#define THORVG_VERSION_STRING "1.0.0"

#define THORVG_PARTIAL_RENDER_SUPPORT 1

#define THORVG_GL_RASTER_SUPPORT 1

#define THORVG_PNG_LOADER_SUPPORT 1
#define THORVG_JPG_LOADER_SUPPORT 1
#define THORVG_WEBP_LOADER_SUPPORT 1
#define THORVG_SVG_LOADER_SUPPORT 1
#define THORVG_LOTTIE_LOADER_SUPPORT 1

#define WIN32_LEAN_AND_MEAN 1

#define THORVG_LOG_ENABLED 1

#define THORVG_FILE_IO_SUPPORT 1